import { availabilityNote, reportExportDescriptors } from "./domain"
import type { ReportCatalogItem, ReportDefinition, ReportId } from "./types"

export const REPORT_REGISTRY: readonly ReportDefinition[] = [
  {
    id: "profit-loss",
    category: "financial",
    title: "Profit and loss",
    description: "Resume ingresos, costo vendido, gastos generales y resultado operativo.",
    dateBasis: "saleDate",
    supportedFilters: ["preset", "startDate", "endDate", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "sales-profitability",
    category: "financial",
    title: "Rentabilidad de ventas",
    description: "Detalle por venta usando snapshots congelados de costo y profit.",
    dateBasis: "saleDate",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleId", "buyer", "includeVoided", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "gross-margin-by-vehicle",
    category: "financial",
    title: "Margen bruto por vehiculo",
    description: "Margen, ROI y profit por venta cerrada.",
    dateBasis: "saleDate",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleId", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "inventory-value",
    category: "financial",
    title: "Valor actual de inventario",
    description: "Costo vigente del inventario no vendido a estado actual.",
    dateBasis: "currentState",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [
      availabilityNote("currentStateOnly", "Este reporte muestra inventario actual y no reconstruye cortes historicos."),
    ],
  },
  {
    id: "cost-breakdown-by-vehicle",
    category: "financial",
    title: "Desglose de costo por vehiculo",
    description: "Compra, reparacion y gasto capitalizado por unidad.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleId", "vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [
      availabilityNote("currentStateOnly", "El desglose refleja costos activos del vehiculo en estado actual."),
    ],
  },
  {
    id: "cash-activity",
    category: "financial",
    title: "Actividad de efectivo",
    description: "Ventas cobradas y pagos salientes capturados por periodo.",
    dateBasis: "paymentDate",
    supportedFilters: ["preset", "startDate", "endDate", "paymentMethod", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "current-inventory",
    category: "inventory",
    title: "Inventario actual",
    description: "Vehiculos vigentes no vendidos con costo y dias en inventario.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "inventory-aging",
    category: "inventory",
    title: "Antiguedad de inventario",
    description: "Bucket de 0-30, 31-60, 61-90 y mas de 90 dias.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "vehicles-by-status",
    category: "operations",
    title: "Vehiculos por estatus",
    description: "Conteo y detalle de vehiculos agrupados por estatus actual.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "vehicles-without-title",
    category: "inventory",
    title: "Vehiculos sin titulo en mano",
    description: "Unidades actuales cuyo titulo fisico aun no esta disponible.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "inventory-without-list-price",
    category: "inventory",
    title: "Inventario sin precio de lista",
    description: "Vehiculos actuales sin asking price configurado.",
    dateBasis: "currentState",
    supportedFilters: ["vehicleStatusId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "missing-identifiers",
    category: "audit",
    title: "Identificadores faltantes",
    description: "VIN, stock, titulo y precio faltantes en inventario activo.",
    dateBasis: "currentState",
    supportedFilters: ["missingField", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "accounts-payable",
    category: "payablesPayments",
    title: "Cuentas por pagar",
    description: "Obligaciones activas menos aplicaciones activas de pago.",
    dateBasis: "purchaseDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "reportStatus", "search", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("uncapturedDueDate", "Las fechas de vencimiento no se capturan en el sistema actual.")],
  },
  {
    id: "payment-history",
    category: "payablesPayments",
    title: "Historial de pagos",
    description: "Pagos emitidos, metodo, moneda, aplicaciones y estatus.",
    dateBasis: "paymentDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "paymentMethod", "includeVoided", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "unpaid-obligations",
    category: "payablesPayments",
    title: "Obligaciones sin pagar",
    description: "Documentos por pagar con saldo completo pendiente.",
    dateBasis: "purchaseDate",
    supportedFilters: ["providerId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("uncapturedDueDate", "Sin fecha de vencimiento capturada; prioriza por fecha de origen.")],
  },
  {
    id: "partially-paid-obligations",
    category: "payablesPayments",
    title: "Obligaciones parcialmente pagadas",
    description: "Documentos con pago aplicado pero saldo pendiente.",
    dateBasis: "purchaseDate",
    supportedFilters: ["providerId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("uncapturedDueDate", "Sin fecha de vencimiento capturada; prioriza por fecha de origen.")],
  },
  {
    id: "paid-obligations",
    category: "payablesPayments",
    title: "Obligaciones pagadas",
    description: "Documentos liquidados por completo con aplicaciones activas.",
    dateBasis: "purchaseDate",
    supportedFilters: ["providerId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "provider-balances",
    category: "payablesPayments",
    title: "Saldos por proveedor",
    description: "Agrupa obligaciones y pagos por proveedor capturado.",
    dateBasis: "purchaseDate",
    supportedFilters: ["providerId", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingProvider", "Los registros sin proveedor se agrupan por separado como sin proveedor.")],
  },
  {
    id: "payment-applications",
    category: "payablesPayments",
    title: "Aplicaciones de pago",
    description: "Detalle de cada aplicacion a compra, reparacion o gasto.",
    dateBasis: "paymentDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "general-expenses",
    category: "expenses",
    title: "Gastos generales",
    description: "Gastos no asociados a vehiculo para operacion del lote.",
    dateBasis: "expenseDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "category", "includeVoided", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingProvider", "Los gastos sin proveedor se muestran por separado.")],
  },
  {
    id: "vehicle-expenses",
    category: "expenses",
    title: "Gastos por vehiculo",
    description: "Gastos capitalizados o asociados a un vehiculo.",
    dateBasis: "expenseDate",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleId", "providerId", "category", "includeVoided", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingProvider", "Los gastos sin proveedor se muestran por separado.")],
  },
  {
    id: "expenses-by-category",
    category: "expenses",
    title: "Gastos por categoria",
    description: "Agrupacion de gastos por categoria operativa.",
    dateBasis: "expenseDate",
    supportedFilters: ["preset", "startDate", "endDate", "category", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingCategory", "Los registros sin categoria valida se agrupan como sin categoria.")],
  },
  {
    id: "expenses-by-provider",
    category: "expenses",
    title: "Gastos por proveedor",
    description: "Agrupacion de gastos por proveedor capturado.",
    dateBasis: "expenseDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingProvider", "Los registros sin proveedor se agrupan como sin proveedor.")],
  },
  {
    id: "deduction-preparation",
    category: "taxPreparation",
    title: "Preparacion de deducciones",
    description: "Separa gasto general y costo capitalizado para revision contable.",
    dateBasis: "expenseDate",
    supportedFilters: ["preset", "startDate", "endDate", "category"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingCategory", "La deducibilidad no se infiere; solo se muestra la categoria capturada.")],
  },
  {
    id: "sales-register",
    category: "sales",
    title: "Registro de ventas",
    description: "Libro de ventas con precio, costo, profit y referencias.",
    dateBasis: "saleDate",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleId", "buyer", "includeVoided", "search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "available",
    availabilityNotes: [],
  },
  {
    id: "sales-tax-preparation",
    category: "taxPreparation",
    title: "Soporte para impuesto sobre ventas",
    description: "Expone ventas y marca campos regulatorios no capturados.",
    dateBasis: "saleDate",
    supportedFilters: ["preset", "startDate", "endDate", "vehicleId", "buyer", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [
      availabilityNote("uncapturedSalesTax", "Sales tax collected no se captura en ventas."),
      availabilityNote("uncapturedJurisdiction", "La jurisdiccion fiscal no se captura en ventas."),
      availabilityNote("uncapturedExemptionStatus", "El estatus de exencion no se captura en ventas."),
      availabilityNote("uncapturedFilingTreatment", "El tratamiento de declaracion no se captura en ventas."),
    ],
  },
  {
    id: "vendor-payments",
    category: "taxPreparation",
    title: "Pagos a proveedores",
    description: "Pagos y obligaciones por proveedor para soporte administrativo.",
    dateBasis: "paymentDate",
    supportedFilters: ["preset", "startDate", "endDate", "providerId", "paymentMethod", "includeVoided"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("missingProvider", "Los pagos sin proveedor se muestran por separado.")],
  },
  {
    id: "administrative-exceptions",
    category: "audit",
    title: "Excepciones administrativas",
    description: "Titulos faltantes, margenes negativos, inventario viejo y faltantes de captura.",
    dateBasis: "currentState",
    supportedFilters: ["search"],
    supportedExports: ["csv", "pdf"],
    roles: ["admin", "lectura"],
    availability: "partial",
    availabilityNotes: [availabilityNote("uncapturedDueDate", "Las fechas de vencimiento no se capturan; se revisa antiguedad del documento.")],
  },
] as const

export function getReportDefinition(reportId: ReportId) {
  return REPORT_REGISTRY.find((item) => item.id === reportId) ?? null
}

export function listReportCatalogItems(): ReportCatalogItem[] {
  return REPORT_REGISTRY.map((definition) => ({
    ...definition,
    exportDescriptors: reportExportDescriptors(definition.supportedExports),
    lastGeneratedAt: null,
  }))
}
